### ISSUE TITLE
How to build to Production

### ISSUE THREAD

**Issue by vitordangelo** [glin/shiny-react-example#5]
Hello.

I run the command to create a build to production:

```sh
npm run build
``` 

But just created a main.js file. How i can deploy this file to a web server?

Thanks

**Comment by glin** [comment]
Hi, you'll have to deploy the entire directory to a web server that supports Shiny apps. A few options for deployment are covered here: https://shiny.rstudio.com/deploy/

**Comment by vitordangelo** [comment]
Is possible integrate shiny with a react app, using a CRA (create react app)?
I tried implement react-router-dom in this example, but is not successful

**Comment by glin** [comment]
I'm not familiar with create-react-app, but I think it's possible. Looking at the CRA readme, the main difference is that the JS bundle is output to `build/` instead of `static/`. You can change where the Shiny app looks for the JS bundle here: https://github.com/glin/shiny-react-example/blob/d078bdc74b54c664d950a0b4220ae76bbb37bbe1/app.R#L25-L28

The CRA dev server config may also need some tweaks to use hot reloading with Shiny, but I'm not sure if that's possible to do without ejecting the config.

**Comment by klar-C** [comment]
Hi glin - would it be possible to give an example as to how to deploy it to e.g. rsconnect (or the online shiny platform)?

The output of npm build is a main.js file which seems to be self-contained. Am I supposed to target that as a script like any other js file?
(I'm assuming the port-proxy method is only used for development reasons and not something doable on a connect server.)
