### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by klar-C** [glin/shiny-react-example#7]
Hi - 

First of all thanks for the example - it helped me a lot.

I have a conceptual question: I'm running a react app which basically uses Shiny as the logic behind it (pretty much like your example). I'm using React as the main construct but then I also have Placeholders (e.g. for Plotly) into which Shiny renders some objects.

Did you ever come across an issue that React slows down under such a constellation - especially when it creates new items into the UI?

E.g. this scenario:
- Create react base app (fast)
- Adding plotly to the registered placeholder (fast)
- Adding new elements to the app through react, e.g. a new tab (very slow)

Once the new tab is rendered the first time it is fast again to switch back and forth - but the first time it is rendered it seems that react is having issues comparing the virtual and the actual DOM because it sees all these new elements from Plotly.

Also the more elements I added through the R-side the slower it seems to get.

Any thoughts would be appreciated.

*Edit*
I think I found the culprit. I'm using below command to bind new elements to shiny (as otherwise - at least until now - I didn't know how else to let Shiny know that the object existed). That causes placeholders and plotlyoutputs to be rerendered.
Shiny.unbindAll
Shiny.bindAll
Did you ever come across this issue when writing your reactable package?

*Edit2*
For future reference: Taking away Shiny.unbindAll solves the issue.

**Comment by glin** [comment]
I can't say if that was your exact issue, but yes, one caveat of mixing Shiny inputs/outputs with a React app is that you have to call `Shiny.bindAll()` and `Shiny.unbindAll()` yourself. `bindAll()` when rendering a Shiny element via React, and `unbindAll()` when that element unmounts. I forget where this is documented officially, but Joe has a good explanation of it here: https://community.rstudio.com/t/what-is-the-purpose-of-using-shiny-bindall/14489/2

I'd also recommend calling `bindAll()` and `unbindAll()` on the exact element like `bindAll(el)` and `unbindAll(el)`, since they'll search the entire page by default. reactable has one example of this with a class component here: https://github.com/glin/reactable/blob/a787d3458a113bc7af0f41cd8125e8499154f3e7/srcjs/Reactable.v2.js#L208-L218

**Comment by klar-C** [comment]
Greg - thanks for the response.

The issue I encountered with unbindAll(el) is that even when targeting certain elements, plotly (r plugin) seemed to rerender everything (also plots that are not referenced through the el) which made new bindAll() calls prohibitively slow. I confirmed that through the Chrome performance tracker/snapshot.

So for now I'm stuck with solely running bindAll each time, which seems to perform.

One drawback is that, once elements get hidden, and a bindall is called, then elements that don't have suspendWhenHidden=F for outputoptions loose their binding. So for now I need to set suspendwhenhidden=F for everything. (Which then again seems to cascade into more issues such as https://github.com/rstudio/shiny/issues/3293 which makes me loose the ability to track render progress).

I have not tried the scoped bindall(el) yet so not sure if the issue exists there too. But I'd be interested if you have come across above issues as well.

Overall though I'm becoming a big fan of using React for (almost) everything on the browser side and keeping R Shiny as a state/data manager.
